#!/bin/bash
echo "Creating token accounts..."
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "bcd5f08f-aeaf-4ed2-aeac-d73c618d4da7", "balance": 10000 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "8d58cd59-8504-4e2f-acc7-ec324fd23bfe", "balance": 0 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "28aeeec5-1c8c-40ab-8c48-045b8d6a2fad", "balance": 0 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "2084cd17-0af4-43a0-a886-a216d6b2ac08", "balance": 0 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "9993cab3-0386-4c79-899a-2692567c8701", "balance": 0 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "2d61f75e-5c01-4359-bc42-9988393c1816", "balance": 0 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "8a50dedb-c1d0-43e3-abf8-8ef2bd08d922", "balance": 500 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "b79328bb-8f61-4c5c-93d8-f7a335c54459", "balance": 1000 }]}'
echo "Adding participants..."
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.Manufacturer", "bpId": "MF1", "title": "Manufacturer", "account": "resource:netsol.innovation.aar.token.model.Account#bcd5f08f-aeaf-4ed2-aeac-d73c618d4da7" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.FinanceCompany", "bpId": "FC1", "title": "Finance Company", "account": "resource:netsol.innovation.aar.token.model.Account#8d58cd59-8504-4e2f-acc7-ec324fd23bfe" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.Dealer", "bpId": "DL1", "title": "Dealer", "account": "resource:netsol.innovation.aar.token.model.Account#28aeeec5-1c8c-40ab-8c48-045b8d6a2fad" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.LegalAuthority", "bpId": "LA1", "title": "Legal Authority", "account": "resource:netsol.innovation.aar.token.model.Account#2084cd17-0af4-43a0-a886-a216d6b2ac08" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.Servicer", "bpId": "SR1", "title": "Servicer", "account": "resource:netsol.innovation.aar.token.model.Account#9993cab3-0386-4c79-899a-2692567c8701" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.Person", "firstName": "Mike", "lastName": "Morton", "contactDetails": { "$class": "netsol.innovation.aar.participants.model.ContactDetails" }, "Dob": "1984-08-10T07:15:35.399Z", "bpId": "5332", "title": "Mike Morton", "account": "resource:netsol.innovation.aar.token.model.Account#2d61f75e-5c01-4359-bc42-9988393c1816" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.Renter", "firstName": "John", "lastName": "Smith", "contactDetails": { "$class": "netsol.innovation.aar.participants.model.ContactDetails" }, "Dob": "1980-08-10T07:15:35.399Z", "bpId": "RNTR1", "title": "John Smith", "account": "resource:netsol.innovation.aar.token.model.Account#8a50dedb-c1d0-43e3-abf8-8ef2bd08d922" }'
composer participant add -c admin@aar -d '{ "$class": "netsol.innovation.aar.participants.model.FleetOwner", "bpId": "FO1", "title": "FO1", "account": "resource:netsol.innovation.aar.token.model.Account#b79328bb-8f61-4c5c-93d8-f7a335c54459" }'
echo "Issuing identities..."
composer identity issue --card admin@aar -u manufacturer -a netsol.innovation.aar.participants.model.Manufacturer#MF1
composer identity issue --card admin@aar -u financecompany -a netsol.innovation.aar.participants.model.FinanceCompany#FC1
composer identity issue --card admin@aar -u dealer -a netsol.innovation.aar.participants.model.Dealer#DL1
composer identity issue --card admin@aar -u legal -a netsol.innovation.aar.participants.model.LegalAuthority#LA1
composer identity issue --card admin@aar -u servicer -a netsol.innovation.aar.participants.model.Servicer#SR1
composer identity issue --card admin@aar -u mike -a netsol.innovation.aar.participants.model.Person#5332
composer identity issue --card admin@aar -u renter -a netsol.innovation.aar.participants.model.Renter#RNTR1
composer identity issue --card admin@aar -u fleetowner -a netsol.innovation.aar.participants.model.FleetOwner#FO1
echo "Adding one car for dev purposes.. VIN001"
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.token.model.Account", "resources": [{ "$class": "netsol.innovation.aar.token.model.Account", "address": "eef18513-9c70-488b-bfdc-6e8f6a478caa", "balance": 1 }]}'
composer transaction submit --card admin@aar -d '{"$class": "org.hyperledger.composer.system.AddAsset", "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#netsol.innovation.aar.vehicle.model.Vehicle", "resources": [{ "$class": "netsol.innovation.aar.vehicle.model.Vehicle", "vin": "VIN001", "locked": false, "vehicleDetails": { "$class": "netsol.innovation.aar.vehicle.model.VehicleDetails", "make": "Toyota", "model": "Camry" }, "account": "resource:netsol.innovation.aar.token.model.Account#eef18513-9c70-488b-bfdc-6e8f6a478caa", "oem": "resource:netsol.innovation.aar.participants.model.Manufacturer#MF1" }]}'