FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# RUN npm install
# If  building  for production
RUN npm install --only=production

# Bundle app source // for prod. For dev we will mount volume on docker run
COPY . .

EXPOSE 3005
CMD ["npm", "start"]