FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./SimulatedDevice/
WORKDIR /app/SimulatedDevice
RUN dotnet restore

# copy and publish app and libraries
WORKDIR /app/
COPY . ./SimulatedDevice/
WORKDIR /app/SimulatedDevice
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime AS runtime
WORKDIR /app
COPY --from=build /app/SimulatedDevice/out ./
COPY --from=build /app/SimulatedDevice/*.txt ./

ENTRYPOINT [ "sh", "-c", "dotnet SimulatedDevice.dll $VIN $MILAGE $MOVING $AVG_MILES_P_HOUR $HBREAK_PROB $AVG_FUEL_CONS $CONN_STR $ROUTE_FILE" ]